version: '3.8'

services:
  databasenet:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'databasenet'
      POSTGRES_USER: 'netisanov'
      POSTGRES_PASSWORD: 'q34502010'
    ports:
      - 5432:5432

volumes:
  data: