# Generated by Django 3.2.8 on 2021-10-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_coordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='latitude',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='longitude',
            field=models.FloatField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='web_app.person'),
        ),
    ]
