# Generated by Django 3.2.8 on 2021-10-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auto_20211022_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
