# Generated by Django 3.2.8 on 2021-10-23 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_coordinate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='name',
        ),
    ]
