# Generated by Django 3.2.8 on 2021-10-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_remove_coordinate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
